version: '3.9'

services:
  nadwa:
    image: nadwa
    build:
      context: .
      dockerfile: Nadwa/Dockerfile
    environment:
      - REDIS_HOST=redis   
      - REDIS_PORT=6379    
    depends_on:
      - redis
    ports:
      - "5000:80"       

  redis:
    image: redis
    ports:
      - "6379:6379"      
